name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Unit tests.
        run: go test -short -coverprofile coverage.txt -covermode=atomic  ./...

      - name: Push Test coverage
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Tag Release
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
